# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=20)),
                ('CNPJ', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedido', models.DateField()),
                ('preco', models.FloatField()),
                ('prioridade', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('qtd_tentativas', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cliente')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('dataNascimento', models.DateField()),
                ('CPF', models.CharField(max_length=45)),
                ('salario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.CharField(max_length=45)),
                ('dataRecebimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('precoBase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('tipoUsuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Funcionario')),
                ('status', models.IntegerField()),
            ],
            bases=('home.funcionario',),
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Funcionario')),
            ],
            bases=('home.funcionario',),
        ),
        migrations.AddField(
            model_name='entrega',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Recibo'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Regiao'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Entregador'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Entregador'),
        ),
    ]
