# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160219192100 on 2016-03-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
