# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160219192100 on 2016-05-27 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default='AAA-0000', max_length=8),
        ),
    ]
