# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160219192100 on 2016-06-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160527_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
